### ISSUE TITLE
Integrate CLA Bot with FINOS Pure/Alloy instance of GitLab

### ISSUE THREAD

**Issue by mcleo-d** [ScottLogic/gitlab-cla-bot#35]
## Description
FINOS needs the GitLab CLA Bot team to help integrate the system into a private instance of GitLab to help complete the following development story ...

* https://github.com/finos/open-developer-platform/issues/15

## Contact Details
Please leave a comment on https://github.com/finos/open-developer-platform/issues/15 when you're ready to engage or contact the following FINOS team members direct ...

* https://github.com/maoo
* https://github.com/mcleo-d
* https://github.com/brooklynrob

**Comment by maoo** [comment]
Yay, first successful deployment! As usual, I had to spend 2/3 hours on AWS configuration. I'm adding below the list of operations I performed, would be great to add them to the project `README.md`.

I'm going to play a bit with the bot now, so I can find a way to configure it for the Alloy initiative.

Please find below the installation steps I followed and some simple suggestions to make deployment process smoother.

------

## AWS Setup
1. Create a user on AWS via IAM dashboard (only enable programmatic access)
2. Assign `AWSLambdaFullAccess`, `IAMFullAccess`, `AWSCloudFormationFullAccess`, `AmazonAPIGatewayInvokeFullAccess` and `AmazonS3FullAccess` to the new user
3. Copy `Access key ID` and `Secrect access key`

## GitLab Setup
1. Create a new user (ie "CLA Bot")
2. Create an `Impersonation Token` with scopes `api`, `read_user` and `read_repository`

## Checkout code and deploy
```
git clone git@github.com:ScottLogic/gitlab-cla-bot.git
cd gitlab-cla-bot

npm install -g serverless

# Make sure to backup the ~/.aws folder, before running the next command
serverless config credentials --provider aws --key <Access key ID> --secret <Secrect access key>

# Set the GitLab Token in serverless.yml
sed -i.bak 's/YOUR_TOKEN_HERE/<GitLab Token>/g' serverless.yml

# Choose a unique S3 name
sed -i.bak 's/gitlab-cla-bot-logs/<New/unique S3 bucket name>/g' serverless.yml

# Deploy using AWS SAM
serverless deploy
```

## Suggestions and improvements
- Rename `serverless.yml` to `serverless.yml.sample` and add `serverless.yml` to `.gitignore`
- Add detailed instructions in the `README.md` re. GitLab/AWS setup (see above)
- Debug IAM Permissions to find the smallest (and most fine-grained) amount of permissions that must be granted to the IAM user (see above, AWS Setup, step #2)

**Comment by maoo** [comment]
Discovered a common issue with SAM; on every `serverless deploy` command, I get a:

```
  An error occurred: GitlabClaBotLoggingBucket - finos-gitlab-cla-bot-logs already exists.
```

Found a simple solution on https://www.npmjs.com/package/serverless-plugin-existing-s3 and submitted a PR on https://github.com/ScottLogic/gitlab-cla-bot/pull/36

**Comment by maoo** [comment]
I'm stuck on a 401 error logged in CloudWatch:

```
    "errorType": "Error",
    "errorMessage": "Error: API request https://gitlab.com/api/v4/projects/14/merge_requests/1 failed with status 401",
    "stack": [
        "Error: Error: API request https://gitlab.com/api/v4/projects/14/merge_requests/1 failed with status 401",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
        "    at postError (/var/runtime/CallbackContext.js:30:54)",
        "    at callback (/var/runtime/CallbackContext.js:42:7)",
        "    at /var/runtime/CallbackContext.js:105:16",
        "    at Runtime.handler (/var/task/src/index.js:71:5)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
```

I tried to:
1. Make the `CLA Bot` GitLab user an admin
2. Add `sudo` scope to the GitLab token created

But none of the solutions seem to work; any idea what could be the issue?

**Comment by maoo** [comment]
401 is fixed, thanks to @mcleo-d for spotting the issue! Here's the PR - https://github.com/ScottLogic/gitlab-cla-bot/pull/37 , which allows to configure the GitLab instance domain (in our case, it's not gitlab.com, updated configuration docs above)

**Comment by maoo** [comment]
@ColinEberhardt @sehaswell - I did some good progress with the deployment, see https://github.com/ScottLogic/gitlab-cla-bot/issues/35#issuecomment-584567846 . However, I still get an error: `Error: A mechanism for verifying contributors has not been specified`.

Maybe I'm using the wrong configuration in `.clabot` as pointer to the contributors list? I'm currently using `"contributorListUrl": "<contributors.json raw URL>",`, could you please confirm that is correct?

Thank you in advance!

**Comment by sehaswell** [comment]
> ... I still get an error: `Error: A mechanism for verifying contributors has not been specified`.
> 
> Maybe I'm using the wrong configuration in `.clabot` as pointer to the contributors list? I'm currently using `"contributorListUrl": "<contributors.json raw URL>",`, could you please confirm that is correct?
> 
> Thank you in advance!
Hi @maoo,
Firstly thanks for your PRs :)

The contributionVerifier module is next on my list of things to unit test, but I can see that it is looking for an object property "contributors"  and then checking if the value is a URL so I suspect changing "contributorListUrl" to "contributors" might do the trick, or at least move you on to the next bug.

For info I have mostly been testing against an array of Gitlab usernames that looks like:
````
{
  "contributors": ["userOne"]
}
````

**Comment by maoo** [comment]
Thanks @sehaswell , that worked! And I got a `cla-signed` label, yay!

I had to use a gist file, because when I tried to use a file hosted by a GitLab repository, I got a 406:

`Error: API request https://gitlab.alloy.finos.org/maoo/mao-rob-test/raw/master/contributors.json failed with status 406`

Let me know if you experience this issue, meanwhile I'll contact GitLab support, as it may be something related with our installation.

Question, is it possible to add basic authentication to that call, ie adding a username and password environment variables that can be wired in the call? This way, I could host the `contributors.json` file in a private GitHub repository (as we currently do for the cla-bot).

Thanks!

**Comment by maoo** [comment]
Here's the gist I used as contributors list - https://gist.github.com/maoo/2b9c9deec284621940656cb22674ef37

**Comment by sehaswell** [comment]
Glad you've got there :)
The 406 sounds like something that could be fixable with the right headers - I don't know if Richard tested out this retrieval method much, so it's possible that twenty minutes and a bit of playing with Postman would give us a solution.

**Comment by maoo** [comment]
Thanks @sehaswell ! Please let me know if you manage to fetch the contributors list from a private GitLab repo; at FINOS we're currently using a public GitHub URL (see https://github.com/ScottLogic/gitlab-cla-bot/issues/38), which is not a viable solution.

**Comment by maoo** [comment]
@sehaswell @strangerich - any update on this? I'm currently using a private GitLab repo to host the contributions.json file, but I still get the 406 ; did you have any luck using this setup? TIA
